# VPN Client Bandwidth Limit Configuration
# Format:
# DEFAULT_LIMIT=20mbit/20mbit
# username_atau_ip=download_rate/upload_rate (atau 50mbit, atau unlimited)
#
# Contoh:
# puncakjaya4=50mbit/50mbit
# admin=unlimited

DEFAULT_LIMIT=20mbit/20mbit
