auth_order    radius
authserver    103.127.133.21:1812
acctserver    103.127.133.21:1813
servers       /etc/radiusclient/servers
dictionary    /etc/radiusclient/dictionary
seqfile       /var/run/radius.seq
mapfile       /etc/radiusclient/port-id-map
bindaddr      *
radius_timeout 10
radius_retries 3
