[global]
port = 1701
access control = no

[lns default]
exclusive = no
ip range = 192.168.20.10-192.168.20.250
local ip = 192.168.20.1
length bit = yes
require authentication = yes
name = l2tpd
pppoptfile = /etc/ppp/options.xl2tpd
